#!/usr/bin/env python3
"""
gen_index.py - Extract VX_API / static inline declarations + doc comments from headers.
Usage:
    python3 gen_index.py include/          -> prints index to stdout
    python3 gen_index.py include/ -o INDEX.md
"""

import re
import sys
import argparse
from pathlib import Path

# ── config ────────────────────────────────────────────────────────────────────

# Prefixes that mark a public declaration
DECL_MARKERS = ("VX_API", "static inline", "static __inline")

# Max lines to look *back* for a doc comment block
COMMENT_LOOKBACK = 20

# ── helpers ───────────────────────────────────────────────────────────────────

def extract_doc_comment(lines: list[str], decl_line_idx: int) -> str:
    """
    Walk backwards from decl_line_idx to find a /* */ or /** */ block
    immediately preceding the declaration (ignoring blank lines).
    Returns the comment as a single cleaned string, or "" if none found.
    """
    i = decl_line_idx - 1
    # skip blank lines between comment and decl
    while i >= 0 and lines[i].strip() == "":
        i -= 1

    if i < 0 or not lines[i].rstrip().endswith("*/"):
        return ""

    # walk up to find the opening /*
    end = i
    while i >= 0 and "/*" not in lines[i]:
        i -= 1
    if i < 0:
        return ""

    block = lines[i : end + 1]
    # strip * prefixes and leading/trailing whitespace per line
    cleaned = []
    for ln in block:
        ln = ln.strip()
        ln = re.sub(r"^/\*+\s?", "", ln)   # opening  /**  /*
        ln = re.sub(r"\*+/$", "", ln)       # closing  */
        ln = re.sub(r"^\*\s?", "", ln)      # middle   * text
        ln = ln.strip()
        if ln:
            cleaned.append(ln)
    return " ".join(cleaned)


def parse_decl_name(decl: str) -> str:
    """
    Pull the function/macro name from a declaration line.
    E.g.:  VX_API bool vx_fs_is_path_protected(const char *target);
           -> vx_fs_is_path_protected
    """
    # strip marker prefixes
    s = decl.strip()
    for m in DECL_MARKERS:
        s = s.replace(m, "")
    # grab the last identifier before '('
    m = re.search(r"(\w+)\s*\(", s)
    return m.group(1) if m else s.split()[-1].rstrip(";")


def collect_decls(header: Path) -> list[dict]:
    lines = header.read_text(encoding="utf-8", errors="replace").splitlines()
    results = []
    for i, line in enumerate(lines):
        stripped = line.strip()
        if any(stripped.startswith(mk) for mk in DECL_MARKERS):
            name = parse_decl_name(stripped)
            # collapse multi-line decl to one line for display
            decl_display = stripped.rstrip("\\").strip()
            comment = extract_doc_comment(lines, i)
            results.append({
                "file":    header.name,
                "name":    name,
                "decl":    decl_display,
                "comment": comment,
            })
    return results


# ── formatting ────────────────────────────────────────────────────────────────

def render_markdown(entries: list[dict], by_file: bool = True) -> str:
    lines = ["# vx API Index", ""]
    lines += [
        "> Auto-generated by `gen_index.py`. "
        "Add `/* */` doc comments above declarations to populate the Description column.",
        "",
    ]

    if by_file:
        from itertools import groupby
        entries_sorted = sorted(entries, key=lambda e: e["file"])
        for file, group in groupby(entries_sorted, key=lambda e: e["file"]):
            lines.append(f"## `{file}`")
            lines.append("")
            lines.append(f"| Name | Description |")
            lines.append(f"|------|-------------|")
            for e in group:
                desc = e["comment"] if e["comment"] else "—"
                lines.append(f"| `{e['name']}` | {desc} |")
            lines.append("")
    else:
        lines.append("| File | Name | Description |")
        lines.append("|------|------|-------------|")
        for e in sorted(entries, key=lambda e: e["name"]):
            desc = e["comment"] if e["comment"] else "—"
            lines.append(f"| `{e['file']}` | `{e['name']}` | {desc} |")
        lines.append("")

    undoc = [e for e in entries if not e["comment"]]
    if undoc:
        lines.append("---")
        lines.append(f"## ⚠ Undocumented ({len(undoc)})")
        lines.append("")
        lines.append("These declarations have no doc comment yet:")
        lines.append("")
        for e in sorted(undoc, key=lambda e: e["name"]):
            lines.append(f"- `{e['name']}` — *{e['file']}*")
        lines.append("")

    return "\n".join(lines)


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description="Generate API index from C headers.")
    ap.add_argument("include_dir", help="Path to include/ directory")
    ap.add_argument("-o", "--output", help="Output file (default: stdout)")
    ap.add_argument("--flat", action="store_true",
                    help="Single flat table instead of per-file sections")
    args = ap.parse_args()

    include = Path(args.include_dir)
    if not include.is_dir():
        sys.exit(f"error: {include} is not a directory")

    headers = sorted(include.rglob("*.h"))
    if not headers:
        sys.exit(f"error: no .h files found under {include}")

    all_entries = []
    for h in headers:
        all_entries.extend(collect_decls(h))

    print(f"Scanned {len(headers)} headers, found {len(all_entries)} declarations.",
          file=sys.stderr)

    output = render_markdown(all_entries, by_file=not args.flat)

    if args.output:
        Path(args.output).write_text(output, encoding="utf-8")
        print(f"Written to {args.output}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
